/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.project.MenuPrincipal;

import com.project.Metodos.Metodos;
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author aspxe
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGrado6 = new javax.swing.JLabel();
        txtGrado6 = new javax.swing.JTextField();
        lblGrado5 = new javax.swing.JLabel();
        txtGrado5 = new javax.swing.JTextField();
        lblGrado4 = new javax.swing.JLabel();
        txtGrado4 = new javax.swing.JTextField();
        lblGrado3 = new javax.swing.JLabel();
        txtGrado3 = new javax.swing.JTextField();
        lblGrado2 = new javax.swing.JLabel();
        txtGrado2 = new javax.swing.JTextField();
        lblGrado1 = new javax.swing.JLabel();
        txtGrado1 = new javax.swing.JTextField();
        lblConstante = new javax.swing.JLabel();
        txtConstante = new javax.swing.JTextField();
        lblDecimales = new javax.swing.JLabel();
        cbDecimales = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        lblErrorRelativo = new javax.swing.JLabel();
        txtErrorRelativo = new javax.swing.JTextField();
        lblNumeroInicio = new javax.swing.JLabel();
        txtNumeroIncio = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(600, 300));
        setMaximumSize(new java.awt.Dimension(600, 600));
        setMinimumSize(new java.awt.Dimension(10, 10));
        setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        lblGrado6.setText("Grado 6");
        getContentPane().add(lblGrado6);
        lblGrado6.setBounds(25, 26, 80, 18);

        txtGrado6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGrado6KeyTyped(evt);
            }
        });
        getContentPane().add(txtGrado6);
        txtGrado6.setBounds(25, 62, 100, 24);

        lblGrado5.setText("Grado 5");
        getContentPane().add(lblGrado5);
        lblGrado5.setBounds(155, 26, 52, 18);

        txtGrado5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGrado5KeyTyped(evt);
            }
        });
        getContentPane().add(txtGrado5);
        txtGrado5.setBounds(160, 60, 100, 24);

        lblGrado4.setText("Grado 4");
        getContentPane().add(lblGrado4);
        lblGrado4.setBounds(294, 26, 52, 18);

        txtGrado4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGrado4KeyTyped(evt);
            }
        });
        getContentPane().add(txtGrado4);
        txtGrado4.setBounds(294, 62, 64, 24);

        lblGrado3.setText("Grado 3");
        getContentPane().add(lblGrado3);
        lblGrado3.setBounds(25, 104, 52, 18);

        txtGrado3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGrado3KeyTyped(evt);
            }
        });
        getContentPane().add(txtGrado3);
        txtGrado3.setBounds(25, 140, 100, 24);

        lblGrado2.setText("Grado 2");
        getContentPane().add(lblGrado2);
        lblGrado2.setBounds(155, 104, 52, 18);

        txtGrado2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGrado2KeyTyped(evt);
            }
        });
        getContentPane().add(txtGrado2);
        txtGrado2.setBounds(155, 140, 100, 24);

        lblGrado1.setText("Grado 1");
        getContentPane().add(lblGrado1);
        lblGrado1.setBounds(294, 104, 52, 18);

        txtGrado1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGrado1KeyTyped(evt);
            }
        });
        getContentPane().add(txtGrado1);
        txtGrado1.setBounds(294, 140, 64, 24);

        lblConstante.setText("Constante");
        getContentPane().add(lblConstante);
        lblConstante.setBounds(25, 182, 67, 18);

        txtConstante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtConstanteKeyTyped(evt);
            }
        });
        getContentPane().add(txtConstante);
        txtConstante.setBounds(25, 218, 100, 24);

        lblDecimales.setText("Numero de decimales a trabajar");
        getContentPane().add(lblDecimales);
        lblDecimales.setBounds(380, 30, 220, 18);

        cbDecimales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", " " }));
        getContentPane().add(cbDecimales);
        cbDecimales.setBounds(430, 80, 72, 24);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 260, 600, 30);

        lblErrorRelativo.setText("Error relativo");
        getContentPane().add(lblErrorRelativo);
        lblErrorRelativo.setBounds(30, 280, 100, 18);

        txtErrorRelativo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtErrorRelativoKeyTyped(evt);
            }
        });
        getContentPane().add(txtErrorRelativo);
        txtErrorRelativo.setBounds(30, 320, 100, 24);

        lblNumeroInicio.setText("Numero donde se inicia");
        getContentPane().add(lblNumeroInicio);
        lblNumeroInicio.setBounds(240, 280, 180, 18);

        txtNumeroIncio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroIncioKeyTyped(evt);
            }
        });
        getContentPane().add(txtNumeroIncio);
        txtNumeroIncio.setBounds(240, 320, 160, 24);

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular);
        btnCalcular.setBounds(30, 380, 100, 24);

        txt.setColumns(20);
        txt.setRows(5);
        jScrollPane1.setViewportView(txt);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(220, 380, 340, 190);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed

        double grado6 = 0, grado5 = 0, grado4 = 0, grado3 = 0, grado2 = 0, grado1 = 0, constante = 0, numeroInicio = 0, errorRelativo = 0;
        double fx = 0, derivada = 0, errorCalculado = 0, xi = 0;
        String funcion = "", cadenaDerivada = "", cadena = "";
        Metodos m = new Metodos();
        int contador = 1;
        
        if(txtGrado6.getText().equals("")){
            grado6 = 0;
        }else{
            grado6 = Double.parseDouble(txtGrado6.getText());
        }
        if(txtGrado5.getText().equals("")){
            grado5 = 0;
        }else{
            grado5 = Double.parseDouble(txtGrado5.getText());
        }
        if(txtGrado4.getText().equals("")){
            grado4 = 0;
        }else{
            grado4 = Double.parseDouble(txtGrado4.getText());
        }
        if(txtGrado3.getText().equals("")){
            grado3 = 0;
        }else{
            grado3 = Double.parseDouble(txtGrado3.getText());
        }
        if(txtGrado2.getText().equals("")){
            grado2 = 0;
        }else{
            grado2 = Double.parseDouble(txtGrado2.getText());
        }
        if(txtGrado1.getText().equals("")){
            grado1 = 0;
        }else{
            grado1 = Double.parseDouble(txtGrado1.getText());
        }
        if(txtConstante.getText().equals("")){
            constante = 0;
        }else{
            constante = Double.parseDouble(txtConstante.getText());
        }
        if(txtErrorRelativo.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Error relativo no ingresado", "Informacion faltante", JOptionPane.ERROR_MESSAGE);
        }else{
            errorRelativo = Double.parseDouble(txtErrorRelativo.getText());
        }
        if(txtNumeroIncio.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Numero de inicio no ingresado", "Informacion faltante", JOptionPane.ERROR_MESSAGE);
        }else{
            numeroInicio = Double.parseDouble(txtNumeroIncio.getText());
        }
        
        
        
        funcion = m.funcion(grado6, grado5, grado4, grado3, grado2, grado1, constante);
        cadenaDerivada = m.derivada(grado6, grado5, grado4, grado3, grado2, grado1, constante);
        
        cadena += "Funcion: "+funcion+"\n";
        cadena += "Primera derivada de la funcion: "+cadenaDerivada+"\n";
        cadena += "\n\n";
        
        fx = ((grado6*Math.pow(numeroInicio, 6))+(grado5*Math.pow(numeroInicio, 5))+(grado4*Math.pow(numeroInicio, 4))+(grado3*Math.pow(numeroInicio,3))+(grado2*Math.pow(numeroInicio, 2))+(grado1*Math.pow(numeroInicio, 1))+(constante));
        cadena += "f(x)= "+fx+"\n";
        
        derivada = ((grado6*5*Math.pow(numeroInicio, 5))+(grado5*5*Math.pow(numeroInicio, 4))+(grado4*4*Math.pow(numeroInicio, 3))+(grado3*3*Math.pow(numeroInicio, 2))+(grado2*2*Math.pow(numeroInicio, 1))+(grado1));
        cadena += "f'(x)= "+derivada+"\n";
        cadena += "\n\n";
        
        do{
            cadena += "Iteracion numero "+contador+"\n";
            xi = ((numeroInicio)-((fx)/(derivada)));
            errorCalculado = Math.abs((((xi)-(numeroInicio))/(xi))*100);
            cadena += "Valor de xi+1: "+xi+"\n";
            cadena += "Error relativo calculado: "+errorCalculado+"\n";
            numeroInicio = xi;
            fx = ((grado6*Math.pow(numeroInicio, 6))+(grado5*Math.pow(numeroInicio, 5))+(grado4*Math.pow(numeroInicio, 4))+(grado3*Math.pow(numeroInicio,3))+(grado2*Math.pow(numeroInicio, 2))+(grado1*Math.pow(numeroInicio, 1))+(constante));
            derivada = ((grado6*5*Math.pow(numeroInicio, 5))+(grado5*5*Math.pow(numeroInicio, 4))+(grado4*4*Math.pow(numeroInicio, 3))+(grado3*3*Math.pow(numeroInicio, 2))+(grado2*2*Math.pow(numeroInicio, 1))+(grado1)); 
            cadena += "\n\n";
            txt.setText(cadena);
            contador++;
        }while(errorCalculado>errorRelativo);
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtGrado6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrado6KeyTyped
        // TODO add your handling code here:
        char letra1 = evt.getKeyChar();
        boolean res = false;
        String cadena1 = "";
        cadena1 += letra1;

        res = cadena1.matches("[[.-]0123456789|[+]0123456789]");
        if (!res) {
            evt.consume();
        }
         
    }//GEN-LAST:event_txtGrado6KeyTyped

    private void txtGrado5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrado5KeyTyped
        // TODO add your handling code here:
        char letra1 = evt.getKeyChar();
        boolean res = false;
        String cadena1 = "";
        cadena1 += letra1;

        res = cadena1.matches("[[.-]0123456789|[+]0123456789]");
        if (!res) {
            evt.consume();
        }
    }//GEN-LAST:event_txtGrado5KeyTyped

    private void txtGrado4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrado4KeyTyped
        // TODO add your handling code here:
        char letra1 = evt.getKeyChar();
        boolean res = false;
        String cadena1 = "";
        cadena1 += letra1;

        res = cadena1.matches("[[.-]0123456789|[+]0123456789]");
        if (!res) {
            evt.consume();
        }
    }//GEN-LAST:event_txtGrado4KeyTyped

    private void txtGrado3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrado3KeyTyped
        // TODO add your handling code here:
        char letra1 = evt.getKeyChar();
        boolean res = false;
        String cadena1 = "";
        cadena1 += letra1;

        res = cadena1.matches("[[.-]0123456789|[+]0123456789]");
        if (!res) {
            evt.consume();
        }
    }//GEN-LAST:event_txtGrado3KeyTyped

    private void txtGrado2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrado2KeyTyped
        // TODO add your handling code here:
        char letra1 = evt.getKeyChar();
        boolean res = false;
        String cadena1 = "";
        cadena1 += letra1;

        res = cadena1.matches("[[.-]0123456789|[+]0123456789]");
        if (!res) {
            evt.consume();
        }
    }//GEN-LAST:event_txtGrado2KeyTyped

    private void txtGrado1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrado1KeyTyped
        // TODO add your handling code here:
        char letra1 = evt.getKeyChar();
        boolean res = false;
        String cadena1 = "";
        cadena1 += letra1;

        res = cadena1.matches("[[.-]0123456789|[+]0123456789]");
        if (!res) {
            evt.consume();
        }
    }//GEN-LAST:event_txtGrado1KeyTyped

    private void txtConstanteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConstanteKeyTyped
        // TODO add your handling code here:
        char letra1 = evt.getKeyChar();
        boolean res = false;
        String cadena1 = "";
        cadena1 += letra1;

        res = cadena1.matches("[[.-]0123456789|[+]0123456789]");
        if (!res) {
            evt.consume();
        }
    }//GEN-LAST:event_txtConstanteKeyTyped

    private void txtErrorRelativoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtErrorRelativoKeyTyped
        // TODO add your handling code here:
        char letra1 = evt.getKeyChar();
        boolean res = false;
        String cadena1 = "";
        cadena1 += letra1;

        res = cadena1.matches("[[.-]0123456789|[+]0123456789]");
        if (!res) {
            evt.consume();
        }
    }//GEN-LAST:event_txtErrorRelativoKeyTyped

    private void txtNumeroIncioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroIncioKeyTyped
        // TODO add your handling code here:
        char letra1 = evt.getKeyChar();
        boolean res = false;
        String cadena1 = "";
        cadena1 += letra1;

        res = cadena1.matches("[[.-]0123456789|[+]0123456789]");
        if (!res) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNumeroIncioKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JComboBox<String> cbDecimales;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblConstante;
    private javax.swing.JLabel lblDecimales;
    private javax.swing.JLabel lblErrorRelativo;
    private javax.swing.JLabel lblGrado1;
    private javax.swing.JLabel lblGrado2;
    private javax.swing.JLabel lblGrado3;
    private javax.swing.JLabel lblGrado4;
    private javax.swing.JLabel lblGrado5;
    private javax.swing.JLabel lblGrado6;
    private javax.swing.JLabel lblNumeroInicio;
    private javax.swing.JTextArea txt;
    private javax.swing.JTextField txtConstante;
    private javax.swing.JTextField txtErrorRelativo;
    private javax.swing.JTextField txtGrado1;
    private javax.swing.JTextField txtGrado2;
    private javax.swing.JTextField txtGrado3;
    private javax.swing.JTextField txtGrado4;
    private javax.swing.JTextField txtGrado5;
    private javax.swing.JTextField txtGrado6;
    private javax.swing.JTextField txtNumeroIncio;
    // End of variables declaration//GEN-END:variables
}
